steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--no-optional']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
artifacts:
  objects:
    location: 'gs://s.063.jp/'
    paths: ['dist/*']
